INSERT INTO franchise (name,description) VALUES ('X-Men Trilogy','Its a good trilogy');
INSERT INTO franchise (name,description) VALUES ('Iron Man Verse','decent movies');
INSERT INTO franchise (name,description) VALUES ('Deadpool', 'many profanities');
INSERT INTO movie (movie_title, movie_genre, release_year, director, poster_URL, trailer_link,franchise_id) VALUES ('X-Men', 'action, science fiction', 2000, 'Bryan Singer', 'https://upload.wikimedia.org/wikipedia/en/8/81/X-MenfilmPoster.jpg', 'https://www.youtube.com/watch?v=VNxwlx6etXI',1);
INSERT INTO movie (movie_title, movie_genre, release_year, director, poster_URL, trailer_link,franchise_id) VALUES ('X2', 'action, science fiction', 2003, 'Bryan Singer', 'https://upload.wikimedia.org/wikipedia/en/3/3e/X2_poster.jpg', 'https://www.youtube.com/watch?v=luHcOYS1HxQ',1);
INSERT INTO movie (movie_title, movie_genre, release_year, director, poster_URL, trailer_link,franchise_id) VALUES ('X-Men: The Last Stand', 'action, science fiction', 2006, 'Brett Ratner', 'https://upload.wikimedia.org/wikipedia/en/5/5b/X-Men_The_Last_Stand_theatrical_poster.jpg', 'https://www.youtube.com/watch?v=ZQ0v5dXbw7M',1);
INSERT INTO movie (movie_title, movie_genre, release_year, director, poster_URL, trailer_link,franchise_id) VALUES ('Iron Man', 'action, science fiction', 2008, 'Jon Favreau', 'https://upload.wikimedia.org/wikipedia/en/0/02/Iron_Man_%282008_film%29_poster.jpg', 'https://www.youtube.com/watch?v=8ugaeA-nMTc',2);
INSERT INTO movie (movie_title, movie_genre, release_year, director, poster_URL, trailer_link,franchise_id) VALUES ('The Incredible Hulk', 'action, science fiction', 2008, 'Louis Leterrier', 'https://upload.wikimedia.org/wikipedia/en/f/f0/The_Incredible_Hulk_%28film%29_poster.jpg', 'https://www.youtube.com/watch?v=xbqNb2PFKKA',null);
INSERT INTO movie (movie_title, movie_genre, release_year, director, poster_URL, trailer_link,franchise_id) VALUES ('Iron Man 2', 'action, science fiction', 2010, 'Jon Favreau', 'https://upload.wikimedia.org/wikipedia/en/e/ed/Iron_Man_2_poster.jpg', 'https://www.youtube.com/watch?v=qsRZghNciIo',2);
INSERT INTO movie (movie_title, movie_genre, release_year, director, poster_URL, trailer_link,franchise_id) VALUES ('Thor', 'action, science fiction', 2011, 'Kenneth Branagh', 'https://upload.wikimedia.org/wikipedia/en/9/95/Thor_%28film%29_poster.jpg', 'https://www.youtube.com/watch?v=w1k59SJ_-Uo',null);
INSERT INTO movie (movie_title, movie_genre, release_year, director, poster_URL, trailer_link,franchise_id) VALUES ('Captain America: The First Avenger', 'action, science fiction', 2011, 'Joe Johnston', 'https://upload.wikimedia.org/wikipedia/en/3/37/Captain_America_The_First_Avenger_poster.jpg', 'https://www.youtube.com/watch?v=FkTybqcX-Yo',null);
INSERT INTO movie (movie_title, movie_genre, release_year, director, poster_URL, trailer_link,franchise_id) VALUES ('The Avengers', 'action, science fiction', 2012, 'Joss Whedon', 'https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg', 'https://www.youtube.com/watch?v=eOrNdBpGMv8',null);
INSERT INTO movie (movie_title, movie_genre, release_year, director, poster_URL, trailer_link,franchise_id) VALUES ('Deadpool', 'action, science fiction', 2016, 'Tim Miller', 'https://upload.wikimedia.org/wikipedia/en/2/23/Deadpool_%282016_poster%29.png', 'https://www.youtube.com/watch?v=ByUB4d5OA0o',3);
INSERT INTO movie (movie_title, movie_genre, release_year, director, poster_URL, trailer_link,franchise_id) VALUES ('Deadpool 2', 'action, science fiction', 2018, 'David Leitch', 'https://upload.wikimedia.org/wikipedia/en/c/cf/Deadpool_2_poster.jpg', 'https://www.youtube.com/watch?v=PCf03KXyzIg',3);
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Iron Man', 'Tony Stark', 'Male', 'https://example.com/iron_man.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Captain America', 'Steve Rogers', 'Male', 'https://example.com/captain_america.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Black Widow', 'Natasha Romanoff', 'Female', 'https://example.com/black_widow.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Thor', 'Thor Odinson', 'Male', 'https://example.com/thor.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Hulk', 'Bruce Banner', 'Male', 'https://example.com/hulk.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Spider-Man', 'Peter Parker', 'Male', 'https://example.com/spider_man.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Wolverine', 'Logan', 'Male', 'https://example.com/wolverine.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Storm', 'Ororo Munroe', 'Female', 'https://example.com/storm.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Beast', 'Hank McCoy', 'Male', 'https://example.com/beast.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Cyclops', 'Scott Summers', 'Male', 'https://example.com/cyclops.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Jean Grey', 'Jean Grey', 'Female', 'https://example.com/jean_grey.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Rogue', 'Anna Marie', 'Female', 'https://example.com/rogue.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Gambit', 'Remy LeBeau', 'Male', 'https://example.com/gambit.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Professor X', 'Charles Xavier', 'Male', 'https://example.com/professor_x.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Magneto', 'Erik Lehnsherr', 'Male', 'https://example.com/magneto.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Mystique', 'Raven Darkhölme', 'Female', 'https://example.com/mystique.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Iceman', 'Bobby Drake', 'Male', 'https://example.com/iceman.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Angel', 'Warren Worthington III', 'Male', 'https://example.com/angel.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Nightcrawler', 'Kurt Wagner', 'Male', 'https://example.com/nightcrawler.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Colossus', 'Piotr Rasputin', 'Male', 'https://example.com/colossus.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Deadpool', 'Wade Wilson', 'Male', 'https://example.com/deadpool.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Daredevil', 'Matt Murdock', 'Male', 'https://example.com/daredevil.jpg');
INSERT INTO characters (alias, full_name, gender, picture) VALUES ('Elektra', 'Elektra Natchios', 'Female', 'https://example.com/elektra.jpg');
INSERT INTO movie_characters (movie_id, character_id) VALUES (1,1);
INSERT INTO movie_characters (movie_id, character_id) VALUES (1,2);
INSERT INTO movie_characters (movie_id, character_id) VALUES (1,3);
INSERT INTO movie_characters (movie_id, character_id) VALUES (2,3);
INSERT INTO movie_characters (movie_id, character_id) VALUES (2,4);